app/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import include
from django.urls import path

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("public.urls"), name="public"),
    path("organizations/", include("organizations.urls"), name="organizations"),
]

admin.site.login = staff_member_required(admin.site.login, login_url=settings.LOGIN_URL)
admin.site.index_title = settings.ADMIN_INDEX_TITLE
admin.site.name = settings.ADMIN_NAME
admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_TITLE

app/organizations/urls.py
from django.urls import path

from organizations import views

app_name = "organizations"

urlpatterns = [
    path("", views.OrganizationListView.as_view(), name="list"),
    path("create/", views.OrganizationCreateView.as_view(), name="create"),
    path("<str:organization_name>/", views.OrganizationDetailView.as_view(), name="detail"),
    path("<str:organization_name>/events/create/", views.EventCreateView.as_view(), name="event_create"),
    path("<str:organization_name>/events/<str:event_name>/", views.EventDetailView.as_view(), name="event_detail"),
]

app/common/models.py
import uuid

from django.db import models

from common.managers import BaseManager


class BaseModel(models.Model):
    uuid = models.UUIDField(unique=True, editable=False, default=uuid.uuid4, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = BaseManager()

    class Meta:
        abstract = True

app/organizations/models.py
from django.db import models
from django.urls import reverse_lazy

from common.models import BaseModel
from users.models import User


class Organization(BaseModel):
    name = models.CharField(max_length=512, unique=True)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, related_name="created_organizations", null=True)
    moderators = models.ManyToManyField(User, related_name="moderating_organizations")
    members = models.ManyToManyField(User, related_name="membership_organizations")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy("organizations:detail", kwargs={"organization_name": self.name})


class Event(BaseModel):
    name = models.CharField(max_length=512)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, null=False)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, related_name="created_events", null=True)
    moderators = models.ManyToManyField(User, related_name="moderating_events")
    members = models.ManyToManyField(User, related_name="membership_events")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy(
            "organizations:event_detail",
            kwargs={
                "organization_name": self.organization.name,
                "event_name": self.name
            }
        )

app/users/models.py
from django.contrib.auth.models import AbstractUser

from common.models import BaseModel
from users.managers import UserManager


class User(AbstractUser, BaseModel):
    objects = UserManager()

app/organizations/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import ListView

from organizations.models import Event
from organizations.models import Organization


class OrganizationListView(ListView):
    context_object_name = "organizations"
    model = Organization
    template_name = "organizations/list.html"


class OrganizationCreateView(LoginRequiredMixin, CreateView):
    model = Organization
    template_name = "organizations/create.html"
    fields = [
        "name",
    ]

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.creator = self.request.user
        self.object.save()
        self.object.moderators.add(self.request.user)
        self.object.members.add(self.request.user)
        return redirect(to=self.object.get_absolute_url())


class OrganizationDetailView(DetailView):
    context_object_name = "organization"
    model = Organization
    template_name = "organizations/detail.html"

    def get_object(self, queryset=None):
        return Organization.objects.get(name=self.kwargs.get("organization_name"))


class EventCreateView(LoginRequiredMixin, CreateView):
    model = Event
    template_name = "organizations/event_create.html"
    fields = [
        "name",
    ]

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.creator = self.request.user
        self.object.organization = Organization.objects.get(name=self.kwargs.get("organization_name"))
        self.object.save()
        self.object.moderators.add(self.request.user)
        self.object.members.add(self.request.user)
        return redirect(to=self.object.get_absolute_url())


class EventDetailView(DetailView):
    context_object_name = "event"
    model = Event
    template_name = "organizations/event_detail.html"

    def get_object(self, queryset=None):
        return Event.objects.get(
            organization__name=self.kwargs.get("organization_name"),
            name=self.kwargs.get("event_name")
        )

app/organizations/templates/organizations/base.html
{% extends "base.html" %}

app/organizations/templates/organizations/create.html
{% extends "organizations/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Organization{% endblock %}

{% block content %}
  <div class="container">
    <form class="m-auto w-25" method="post">
      <h2 class="text-center">Create Organization</h2>
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Submit" class="btn btn-lg btn-primary w-100">
    </form>
  </div>
{% endblock %}

app/organizations/templates/organizations/detail.html
{% extends "organizations/base.html" %}

{% block title %}{{ organization.name }}{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="text-center mt-3">{{ organization.name }}</h1>
    <h2>Creator</h2>
    <p>{{ organization.creator }}</p>
    <h2>Moderators</h2>
    <ul>
      {% for moderator in organization.moderators.all %}
        <li>{{ moderator.username }}</li>
      {% endfor %}
    </ul>
    <h2>Members</h2>
    <ul>
      {% for member in organization.members.all %}
        <li>{{ member.username }}</li>
      {% endfor %}
    </ul>
    <h2>Events</h2>
    <ul>
      {% for event in organization.event_set.all %}
        <li><a href="{{ event.get_absolute_url }}">{{ event.name }}</a></li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

app/organizations/templates/organizations/event_create.html
{% extends "organizations/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Event{% endblock %}

{% block content %}
  <div class="container">
    <form class="m-auto w-25" method="post">
      <h2 class="text-center">Create Event</h2>
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Submit" class="btn btn-lg btn-primary w-100">
    </form>
  </div>
{% endblock %}

app/organizations/templates/organizations/event_detail.html
{% extends "organizations/base.html" %}

{% block title %}{{ event.name }}{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="text-center mt-3">{{ event.name }}</h1>
    <h2>Organization</h2>
    <p><a href="{{ event.organization.get_absolute_url }}">{{ event.organization.name }}</a></p>
    <h2>Creator</h2>
    <p>{{ event.creator }}</p>
    <h2>Moderators</h2>
    <ul>
      {% for moderator in event.moderators.all %}
        <li>{{ moderator.username }}</li>
      {% endfor %}
    </ul>
    <h2>Members</h2>
    <ul>
      {% for member in event.members.all %}
        <li>{{ member.username }}</li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

app/organizations/templates/organizations/list.html
{% extends "organizations/base.html" %}

{% block title %}Organizations List{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="text-center mt-3">Organizations List</h1>
    {% if organizations %}
      <ul>
        {% for organization in organizations %}
          <li><a href="{{ organization.get_absolute_url }}">{{ organization.name }}</a></li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No organizations found</p>
    {% endif %}
  </div>
{% endblock %}

app/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{% static 'img/favicon.ico' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  {% block extra_head %}{% endblock extra_head %}
  {% block extra_css %}{% endblock %}
  <title>{% block title %}{% block head_title %}{% endblock head_title %}{% endblock %}</title>
</head>
<body>
  {% include "partials/header.html" %}
  {% include "partials/messages.html" %}
  {% block body %}
    <main class="container">{% block content %}{% endblock %}</main>
  {% endblock %}
  {% block extra_body %}{% endblock extra_body %}
  {% include "partials/footer.html" %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"
          integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"></script>
  <script src="https://unpkg.com/htmx.org@1.9.10"></script>
  <script src="{% static 'js/script.js' %}"></script>
  {% block extra_js %}{% endblock %}
</body>
</html>

app/templates/partials/footer.html
<footer class="container">
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">
    <div class="col mb-3">
      <a href="/" class="d-flex align-items-center mb-3 link-body-emphasis text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <p class="text-body-secondary">© 2024</p>
    </div>

    <div class="col mb-3">

    </div>

    <div class="col mb-3">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
      </ul>
    </div>

    <div class="col mb-3">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
      </ul>
    </div>

    <div class="col mb-3">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
      </ul>
    </div>
  </div>
</footer>

app/templates/partials/header.html
<header class="py-3 mb-4 border-bottom">
  <div class="container d-flex flex-wrap justify-content-center">
    <a href="/" class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto link-body-emphasis text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      <span class="fs-4">Double header</span>
    </a>
    <form class="col-12 col-lg-auto mb-3 mb-lg-0" role="search">
      <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
    </form>
  </div>
</header>

<nav class="py-2 bg-body-tertiary border-bottom">
  <div class="container d-flex flex-wrap">
    <ul class="nav me-auto">
      <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2 active" aria-current="page">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2">About</a></li>
    </ul>
    <ul class="nav">
      {% if user.is_authenticated %}
        <li class="nav-item"><a href="{% url 'account_logout' %}" class="nav-link link-body-emphasis px-2">Logout</a></li>
        <li class="nav-item"><a href="{% url 'public:index' %}" class="nav-link link-body-emphasis px-2">Profile</a></li>
      {% else %}
        <li class="nav-item"><a href="{% url 'account_login' %}" class="nav-link link-body-emphasis px-2">Login</a></li>
        <li class="nav-item"><a href="{% url 'account_signup' %}" class="nav-link link-body-emphasis px-2">Sign up</a></li>
      {% endif %}
      </ul>
  </div>
</nav>

app/templates/partials/messages.html
{% if messages %}
  <div class="container">
    {% for message in messages %}
      <div class="my-3 alert {% if message.tags %}{% if message.tags == 'error' %}alert-danger{% else %}alert-{{ message.tags }}{% endif %}{% endif %} text-center alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  </div>
{% endif %}